doctor_appointments/urls.py
from django.contrib import admin
from django.urls import path, include

from appointment.views.authentication import login, logout, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('appointment.urls')),
    path('authentication/login/', login, name="login"),
    path('authentication/logout/', logout, name="logout"),
    path('authentication/register/', register, name="register"),
]

main/urls.py
from django.urls import path

from main.views import home_page


urlpatterns = [
    path('', home_page, name="home_page"),
]

appointment/models/doctor.py
from django.db import models
from django.core.validators import RegexValidator
from django_countries.fields import CountryField
from django.contrib.auth import get_user_model

from appointment.helpers import get_file_name_ext, generate_random_text
from appointment.constants.doctor import DOCTOR_DEGREE_OPTIONS


User = get_user_model()


def doctor_image_upload_path(instance, file_path):
    """
    Return an upload path for saving doctor profile photos
    :param instance:
    :param file_path:
    :return:
    """
    file_name, file_ext = get_file_name_ext(file_path)
    random_file_name = generate_random_text(file_name)
    final_file_name = f"profile_photos/{random_file_name}"
    return final_file_name


class Doctor(models.Model):

    # Gender Options
    MALE = 'M'
    FEMALE = 'F'

    GENDER_OPTIONS = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    # Pricing Options
    FREE = 'F'
    CUSTOM_PRICE = 'CP'
    PRICING_OPTIONS = (
        (FREE, 'Free'),
        (CUSTOM_PRICE, 'CUSTOM PRICE'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=doctor_image_upload_path, null=True, blank=True)

    phone_validator = RegexValidator(
        regex=r'^\+?\d(9,15)$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )
    phone_number = models.CharField(validators=(phone_validator,), max_length=17, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_OPTIONS, null=True, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    biography = models.TextField(blank=True, null=True)

    clinic_name = models.CharField(max_length=200, null=True, blank=True)
    clinic_address = models.CharField(max_length=200, null=True, blank=True)
    address_line_one = models.CharField(max_length=200, null=True, blank=True)
    address_line_two = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = CountryField(default='GH')
    postal_code = models.CharField(max_length=5, null=True, blank=True)

    pricing = models.CharField(max_length=2, choices=PRICING_OPTIONS, default=FREE, null=True, blank=True)

    services = models.TextField(null=True, blank=True)
    specialization = models.TextField(null=True, blank=True)

    activated = models.BooleanField(default=False)


def clinic_image_file_path(instance, file_path):
    """
    Return a string for clinic image upload
    :param instance:
    :param file_path:
    :return:
    """
    file_name, file_ext = get_file_name_ext(file_path)
    random_file_name = generate_random_text(file_name)
    final_file_name = f"clinic/{random_file_name}"
    return final_file_name


class ClinicImage(models.Model):
    image = models.ImageField(upload_to=clinic_image_file_path)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)


class Education(models.Model):

    degree = models.CharField(max_length=15, choices=DOCTOR_DEGREE_OPTIONS)
    college = models.CharField(max_length=200)
    year_of_completion = models.PositiveIntegerField()
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.college} - {self.degree} - {self.year_of_completion}"


class Award(models.Model):
    name = models.CharField(max_length=200)
    year = models.PositiveIntegerField()
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)


class Experience(models.Model):
    hospital_name = models.CharField(max_length=200)
    from_date = models.DateField()
    to_date = models.DateField()
    designation = models.TextField()
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)


class Membership(models.Model):
    name = models.CharField(max_length=200)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)


class Registration(models.Model):
    name = models.CharField(max_length=200)
    year = models.DateField()
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

appointment/forms/profile.py
from django import forms

from appointment.models.doctor import (
    Doctor, Education, Award, Membership, Registration, Experience, ClinicImage
)


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = "__all__"


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = "__all__"


class AwardForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = "__all__"


class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = "__all__"


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = "__all__"


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = "__all__"


class ClinicImageForm(forms.ModelForm):
    class Meta:
        model = ClinicImage
        fields = "__all__"

appointment/views/profile.py
from django.shortcuts import render, redirect
from django.contrib import messages

from appointment.forms.profile import (
    DoctorForm, EducationForm, ExperienceForm, MembershipForm, AwardForm, RegistrationForm,
    ClinicImageForm
)

from appointment.helpers import get_form_data

EDUCATION_FIELDS = ("degree", "college", "year_of_completion")
CLINIC_IMAGE_FIELDS = ("image",)
AWARD_FIELDS = ("name", "year")
EXPERIENCE_FIELDS = ("hospital_name", "from_date", "to_date", "designation")
MEMBERSHIP_FIELDS = ("name",)
REGISTRATION_FIELDS = ("name", "year")


def doctor_profile(request):
    """
    Return the profile page of the doctor
    :param request:
    :return:
    """
    template = "authentication/profile/doctor/doctor.html"
    form = DoctorForm()
    context = {
        "doctor_form": form,
        "clinic_image_form": ClinicImageForm(),
        "award_form": AwardForm(),
        "experience_form": ExperienceForm(),
        "membership_form": MembershipForm(),
        "registration_form": RegistrationForm()
    }
    return render(request, template, context)


def doctor_profile_update(request):
    """
    Update the profile page of the doctor and return the doctor profile page
    :param request:
    :return:
    """
    if request.method == "POST":
        doctor_form = DoctorForm(request.POST)
        clinic_image_form = ClinicImageForm(get_form_data(CLINIC_IMAGE_FIELDS))
        education_form = EducationForm(get_form_data(EDUCATION_FIELDS))
        award_form = AwardForm(get_form_data(AWARD_FIELDS))
        experience_form = ExperienceForm(get_form_data(EXPERIENCE_FIELDS))
        membership_form = MembershipForm(get_form_data(MEMBERSHIP_FIELDS))
        registration_form = RegistrationForm(get_form_data(REGISTRATION_FIELDS))

        if (
                doctor_form.is_valid() and clinic_image_form.is_valid() and education_form.is_valid() and
                award_form.is_valid() and experience_form.is_valid() and membership_form.is_valid() and
                registration_form.is_valid()
        ):
            doctor_form.save()
            clinic_image_form.save()
            education_form.save()
            award_form.save()
            experience_form.save()
            membership_form.save()
            registration_form.save()
        else:
            import pdb; pdb.set_trace()

        messages.success("Profile Updated Successfully")
        return redirect("profile_doctor")

templates/authentication/profile/doctor/about-me.html
<!-- About Me -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">About Me</h4>
        <div class="form-group mb-0">
            <label>Biography</label>
            <textarea id="{{ doctor_form.biography.id_for_label }}" name="{{ doctor_form.biography.name }}" class="form-control" rows="5">{{ request.user.doctor.biography }}</textarea>
        </div>
    </div>
</div>
<!-- /About Me -->

templates/authentication/profile/doctor/awards.html
<!-- Awards -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Awards</h4>
        <div class="awards-info">
            {% for award in request.user.doctor.award_set.all %}
                <div class="row form-row awards-cont">
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label id="{{ award_form.name.id_for_label }}">Awards</label>
                            <input id="{{ award_form.name.id_for_label }}" name="{{ award_form.name.name }}" value="{{ award.name }}" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label id="{{ award_form.year.id_for_label }}">Year</label>
                            <input id="{{ award_form.year.id_for_label }}" name="{{ award_form.year.name }}" value="{{ award.year }}" type="text" class="form-control">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="add-more">
            <a href="javascript:void(0);" class="add-award"><i class="fa fa-plus-circle"></i> Add More</a>
        </div>
    </div>
</div>
<!-- /Awards -->

templates/authentication/profile/doctor/basic-information.html
{% load utils %}
{% load static %}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Basic Information</h4>
        <div class="row form-row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="change-avatar">
                        <div class="profile-img">
                            <img src="{% static 'assets/img/doctors/doctor-thumb-02.jpg' %}" alt="User Image">
                        </div>
                        <div class="upload-img">
                            <div class="change-photo-btn">
                                <span><i class="fa fa-upload"></i> Upload Photo</span>
                                <input id="{{ doctor_form.photo.id_for_label }}" name="{{ doctor_form.photo.name }}" type="file" class="upload">
                            </div>
                            <small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Username <span class="text-danger">*</span></label>
                    <input value="{{ request.user.username }}" type="text" class="form-control" readonly>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Email <span class="text-danger">*</span></label>
                    <input value="{{ request.user.username }}" type="email" class="form-control" readonly>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>First Name <span class="text-danger">*</span></label>
                    <input value="{{ request.user.first_name }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Last Name <span class="text-danger">*</span></label>
                    <input value="{{ request.user.last_name }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.phone_number.id_for_label }}">Phone Number</label>
                    <input id="{{ doctor_form.phone_number.id_for_label }}" name="{{ doctor_form.phone_number.name }}" value="{{ request.user.doctor.phone_number | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.gender.id_for_label }}">Gender</label>
                    <select id="{{ doctor_form.gender.id_for_label }}" name="{{ doctor_form.gender.name }}" value="{{ request.user.doctor.gender }}" class="form-control select">
                        <option>Select</option>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group mb-0">
                    <label id="{{ doctor_form.date_of_birth.id_for_label }}">Date of Birth</label>
                    <input id="{{ doctor_form.date_of_birth.id_for_label }}" name="{{ doctor_form.date_of_birth.id_for_label }}" value="{{ request.user.doctor.date_of_birth | empty_string }}" type="text" class="form-control">
                </div>
            </div>
        </div>
    </div>
</div>

templates/authentication/profile/doctor/clinic-info.html
{% load utils %}

<!-- Clinic Info -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Clinic Info</h4>
        <div class="row form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.clinic_name.id_for_label }}">Clinic Name</label>
                    <input id="{{ doctor_form.clinic_name.id_for_label }}" name="{{ doctor_form.clinic_name.name }}" value="{{ request.user.doctor.clinic_name | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.clinic_address.id_for_label }}">Clinic Address</label>
                    <input id="{{ doctor_form.clinic_address.id_for_label }}" name="{{ doctor_form.clinic_address.name }}" value="{{ request.user.doctor.clinic_address | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label id="{{ clinic_form.image.id_for_label }}">Clinic Images</label>
                    <form action="#" class="dropzone"></form>
                </div>
                <div class="upload-wrap">
                    {% for image in request.user.doctor.clinicimages_set.all %}
                        <div class="upload-images">
                            <img src="{{ image.url }}" alt="Upload Image">
                            <a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm"><i class="far fa-trash-alt"></i></a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Clinic Info -->

templates/authentication/profile/doctor/contact-details.html
{% load utils %}

<!-- Contact Details -->
<div class="card contact-card">
    <div class="card-body">
        <h4 class="card-title">Contact Details</h4>
        <div class="row form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.address_line_one.id_for_label }}">Address Line 1</label>
                    <input id="{{ doctor_form.address_line_one.id_for_label }}" name="{{ doctor_form.address_line_one.id_for_label }}" value="{{ request.user.doctor.address_line_one | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.address_line_two.id_for_label }}" class="control-label">Address Line 2</label>
                    <input id="{{ doctor_form.address_line_two.id_for_label }}" name="{{ doctor_form.address_line_two.name }}" value="{{ request.user.doctor.address_line_two | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.city.id_for_label }}" class="control-label">City</label>
                    <input id="{{ doctor_form.city.id_for_label }}" name="{{ doctor_form.city.name }}" value="{{ request.user.doctor.city | empty_string }}" type="text" class="form-control">
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.state.id_for_label }}" class="control-label">State / Province</label>
                    <input id="{{ doctor_form.state.id_for_label }}" name="{{ doctor_form.state.name }}" value="{{ request.user.doctor.state | empty_string }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.country.id_for_label }}" class="control-label">Country</label>
                    <input id="{{ doctor_form.country.id_for_label }}" name="{{ doctor_form.country.name }}" value="{{ request.user.doctor.country }}" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label id="{{ doctor_form.postal_code.id_for_label }}" class="control-label">Postal Code</label>
                    <input id="{{ doctor_form.postal_code.id_for_label }}" name="{{ doctor_form.postal_code.name }}" value="{{ request.user.doctor.postal_code | empty_string }}" type="text" class="form-control">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Contact Details -->

templates/authentication/profile/doctor/doctor.html
{% extends 'authentication/profile/base.html' %}

{% block profile_content %}
    <form action="#" method="post">
        {% include 'authentication/profile/doctor/basic-information.html' %}
        {% include 'authentication/profile/doctor/about-me.html' %}
        {% include 'authentication/profile/doctor/clinic-info.html' %}
        {% include 'authentication/profile/doctor/contact-details.html' %}
        {% include 'authentication/profile/doctor/pricing.html' %}
        {% include 'authentication/profile/doctor/services-and-specializations.html' %}
        {% include 'authentication/profile/doctor/education.html' %}
        {% include 'authentication/profile/doctor/experiences.html' %}
        {% include 'authentication/profile/doctor/awards.html' %}
        {% include 'authentication/profile/doctor/memberships.html' %}
        {% include 'authentication/profile/doctor/registrations.html' %}

        <div class="submit-section submit-btn-bottom">
            <button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
        </div>
    </form>

{% endblock profile_content %}

templates/authentication/profile/doctor/education.html
<!-- Education -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Education</h4>
        <div class="education-info">
            <div class="row form-row education-cont">
                <div class="col-12 col-md-10 col-lg-11">
                    {% for education in request.user.doctor.education_set.all %}
                        <div class="row form-row">
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ education_form.degree.id_for_label }}">Degree</label>
                                    <input id="{{ education_form.degree.id_for_label }}" name="{{ education_form.degree.name }}" value="{{ education.degree }}" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ education_form.college.id_for_label }}">College/Institute</label>
                                    <input id="{{ education_form.college.id_for_label }}" name="{{ education_form.college.name }}" value="{{ education.college }}" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ education_form.year_of_completion.id_for_label }}">Year of Completion</label>
                                    <input id="{{ education_form.year_of_completion.id_for_label }}" name="{{ education_form.year_of_completion.name }}" value="{{ education.year_of_completion }}" type="text" class="form-control">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="add-more">
            <a href="javascript:void(0);" class="add-education"><i class="fa fa-plus-circle"></i> Add More</a>
        </div>
    </div>
</div>
<!-- /Education -->

templates/authentication/profile/doctor/experiences.html
<!-- Experience -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Experience</h4>
        <div class="experience-info">
            {% for experience in request.user.doctor.experiences_set %}
                <div class="row form-row experience-cont">
                    <div class="col-12 col-md-10 col-lg-11">
                        <div class="row form-row">
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ experience_form.hospital_name.id_for_label }}">Hospital Name</label>
                                    <input id="{{ experience_form.hospital_name.id_for_label }}" name="{{ experience_form.hospital_name.name }}" value="{{ experience.hospital_name }}" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ experience_form.from_date.id_for_label }}">From</label>
                                    <input id="{{ experience_form.from_date.id_for_label }}" name="{{ experience_form.from_date.name }}" value="{{ experience.from_date }}" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ experience_form.to_date.id_for_label }}">To</label>
                                    <input id="{{ experience_form.to_date.id_for_label }}" name="{{ experience_form.to_date.name }}" value="{{ experience.to_date }}" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="form-group">
                                    <label id="{{ experience_form.designation.id_for_label }}">Designation</label>
                                    <input id="{{ experience_form.designation.id_for_label }}" name="{{ experience_form.designation.name }}" value="{{ experience.designation }}" type="text" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="add-more">
            <a href="javascript:void(0);" class="add-experience"><i class="fa fa-plus-circle"></i> Add More</a>
        </div>
    </div>
</div>
<!-- /Experience -->

templates/authentication/profile/doctor/memberships.html
<!-- Memberships -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Memberships</h4>
        <div class="membership-info">
            {% for membership in request.user.doctor.member_set.all %}
                <div class="row form-row membership-cont">
                    <div class="col-12 col-md-10 col-lg-5">
                        <div class="form-group">
                            <label>Memberships</label>
                            <input value="{{ membership.name }}" type="text" class="form-control">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="add-more">
            <a href="javascript:void(0);" class="add-membership"><i class="fa fa-plus-circle"></i> Add More</a>
        </div>
    </div>
</div>
<!-- /Memberships -->

templates/authentication/profile/doctor/pricing.html
<!-- Pricing -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Pricing</h4>

        <div class="form-group mb-0">
            <div id="pricing_select">
                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" id="price_free" name="rating_option" class="custom-control-input" value="F" checked>
                    <label class="custom-control-label" for="price_free">Free</label>
                </div>
                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" id="price_custom" name="rating_option" value="CP" class="custom-control-input">
                    <label class="custom-control-label" for="price_custom">Custom Price (per hour)</label>
                </div>
            </div>

        </div>

        <div class="row custom_price_cont" id="custom_price_cont" style="display: none;">
            <div class="col-md-4">
                <input type="text" class="form-control" id="custom_rating_input" name="custom_rating_count" value="" placeholder="20">
                <small class="form-text text-muted">Custom price you can add</small>
            </div>
        </div>

    </div>
</div>
<!-- /Pricing -->

templates/authentication/profile/doctor/registrations.html
<!-- Registrations -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Registrations</h4>
        <div class="registrations-info">
            {% for registration in request.user.doctor.registration_set.all %}
                <div class="row form-row reg-cont">
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label>Registrations</label>
                            <input value="{{ registration.name }}" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <label>Year</label>
                            <input value="{{ registration.year }}" type="text" class="form-control">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="add-more">
            <a href="javascript:void(0);" class="add-reg"><i class="fa fa-plus-circle"></i> Add More</a>
        </div>
    </div>
</div>
<!-- /Registrations -->

templates/authentication/profile/doctor/services-and-specializations.html
<!-- Services and Specialization -->
<div class="card services-card">
    <div class="card-body">
        <h4 class="card-title">Services and Specialization</h4>
        <div class="form-group">
            <label>Services</label>
            <input type="text" data-role="tagsinput" class="input-tags form-control" placeholder="Enter Services" name="services" value="{{ request.user.doctor.services }}" id="services">
            <small class="form-text text-muted">Note : Type & Press enter to add new services</small>
        </div>
        <div class="form-group mb-0">
            <label>Specialization </label>
            <input class="input-tags form-control" type="text" data-role="tagsinput" placeholder="Enter Specialization" name="specialist" value="{{ request.user.doctor.specialization }}" id="specialist">
            <small class="form-text text-muted">Note : Type & Press  enter to add new specialization</small>
        </div>
    </div>
</div>
<!-- /Services and Specialization -->